from . import admin_start
from . import admin_courses
from . import admin_modules
from . import admin_lessons
from . import admin_materials
from . import admin_tests
from . import admin_users
from . import admin_payments
from . import admin_reports
from . import admin_feedbacks
from . import admin_settings
